#Build Stage Start

#Specify a base image
# FROM node:alpine as builder 
FROM ubuntu:latest

#Specify a working directory
RUN echo Hell~ ITs shell type command .
RUN ["echo", "Its shell exec type command."]
RUN ["/bin/bash", "-c" , "echo 'Hello~ Its /bin/bash execution in shell type command.'"]
